### ISSUE TITLE
Support Markdown output for comparison table

### ISSUE THREAD

**Issue by brettcannon** [psf/pyperf#113]
https://github.com/python/cpython/pull/28488#issuecomment-925012701 was great to have, but having to paste it in as a code literal block due to it being reST was unfortunate. It would be great is such a table could be pasted into GitHub as a nicely rendered table.

**Comment by corona10** [comment]
@vstinner I would like to add `--table-format=rst|gh`for this feature WDYT?

**Comment by corona10** [comment]
After discussion with @vstinner, I prefer not to change default formatting due to readability in the terminal environment.
