### ISSUE TITLE
Can process run in parallel?

### ISSUE THREAD

**Issue by ylxxwx** [psf/pyperf#160]
A question.
Can the process run in parallel? That means add more processes, we can create bigger qps for the performance test.
If the processes can't run in parallel, what is the purpose we support -p [num]?

**Comment by corona10** [comment]
Well, I am on the same side with @vstinner 
We can provide such an option as optional until we know the use case of such an option. 
I am conservative in providing such options.
Our biggest user is [pyperformance](https://github.com/python/pyperformance), but I am sure that they want accuracy more than fast execution.

**Comment by ylxxwx** [comment]
Thanks for the reply. I am thinking if we can make pyperf to run load test as well with ability to generate request with certain qps. Another thought about that, or another project for that?

**Comment by corona10** [comment]
> if we can make pyperf to run load test as well with ability to generate request with certain qps.

If you are considering load tests for specific tests, why are you considering using pyperf instead of load testing tools?
I think that pyperf measures the performance of python code rather than measuring stress-test for external services.
