### ISSUE TITLE
Include `CONFIG_ARGS` in Metadata

### ISSUE THREAD

**Issue by JeffersGlass** [psf/pyperf#179]
It would be useful to have the information from the `CONFIG_ARGS` variable in the metadata for a benchmark file.

The use case is: determining whether two benchmarks were built from the same Python commit and built with the same options (specifically with regards to the new JIT and PGO).

For more context - I am experimenting with paralleling `pyperformance` across several machines, and for efficiency I am caching several builds of Python on each machine. In order to generate useful comparison data between many different benchmark files, it's useful to extract the commit, JIT and PGO status from the benchmark files themselves.

If there's a better way to determine that data, I'd be open to that.

I have a branch which adds in this info, if it would be useful to submit a PR.

**Comment by vstinner** [comment]
Do you want to propose a PR for that?

**Comment by JeffersGlass** [comment]
Sure! I've opened #180, which is linked to this issue.

**Comment by vstinner** [comment]
Fixed by https://github.com/psf/pyperf/commit/9a99cbe00a985494a273db5af2c809892972f81c
