### ISSUE TITLE
Minor issue regarding memory units (kB vs KiB)

### ISSUE THREAD

**Issue by yngvem** [psf/pyperf#198]
The units in the output when `track-memory` is enabled say `kB` and `MB`. However, as far as I can tell, the correct units are KiB and MiB? It's a minor issue, and might not be worth changing due to the hassle of changing the output for downstream applications, but I found it confusing at first that the summary didn't match up with the actual numbers in the JSON file.

I wasn't sure if it was worth opening an issue for such a minor issue, but I thought it might be worth making a concious decision on whether to use precise SI units.

Sorry if there's already been a discussion on this, I tried looking but I couldn't find anything.

**Comment by vstinner** [comment]
Do you want to propose a pull request fixing the issue?

**Comment by yngvem** [comment]
I can give it a shot
