### ISSUE TITLE
Incorrect standard error

### ISSUE THREAD

**Issue by fzakaria** [psf/pyperf#203]
https://github.com/psf/pyperf/blob/bf02a8b7cc45a47897359681c844b4c507afc552/pyperf/_cli.py#L290

The docs link to https://en.wikipedia.org/wiki/Standard_error which claim it's: standard deviation / square-root(n).

pyperf seems to be only reporting the standard deviation?

Not sure how to use this information along with the t-score to get my confidence intervals.

**Comment by vstinner** [comment]
Did you try the https://pyperf.readthedocs.io/en/latest/cli.html#stats-cmd command?

The https://pyperf.readthedocs.io/en/latest/cli.html#compare-to-cmd command computes also the t-test:

> pyperf determines whether two samples differ significantly using a [Student’s two-sample, two-tailed t-test](https://en.wikipedia.org/wiki/Student's_t-test) with alpha equals to 0.95.

**Comment by fzakaria** [comment]
I tried those commands; they do show the t-test value.
My issue I opened was because the documentation claims that the stdev shown is the "Standard Error" (it even links to the wiki page for Standard Error) but is in fact the **sampled stdev**.

![image](https://github.com/user-attachments/assets/38142506-446b-44f4-9f35-36f94bef7e84)

Showing it as +- is a bit incorrect I felt. It probably needs to then be used with the t-score for a 95% confidence interval?
Anyways; if i'm wrong since i'm also poor at statistics that also makes sense.
I was using pyperformance to benchmark some stuff and wanted to highlight something I found confusing.

**Comment by vstinner** [comment]
Oh, stdev() is the standard deviation: https://docs.python.org/dev/library/statistics.html#statistics.stdev

**Comment by fzakaria** [comment]
Right and that's being reported as the Standard Error on the API was my read.

<img width="1341" alt="Screenshot 2024-09-16 at 1 49 07 PM" src="https://github.com/user-attachments/assets/ef2d197c-4f7d-4f1d-87dc-4b285b99d4d1">

**Comment by vstinner** [comment]
I think that there is a mistake in the link: I wrote https://github.com/psf/pyperf/pull/204 to fix the doc.
