### ISSUE TITLE
Handling return from benchmarked functions

### ISSUE THREAD

**Issue by adamjhc** [psf/pyperf#73]
Hi, is there any way to handle the output of a function while it is being benchmarked by `runner.bench_func`?

Something like:

```python
benchmark, output = runner.bench_func("Test", func)
```

or

```python
benchmark = runner.bench_func("Test", func)
output = benchmark.get_output()
```

I understand this assumes the function is deterministic but having the option would be nice.

Thanks!

**Comment by vstinner** [comment]
bench_func() calls the function many times. The result cannot be returned since it's an unknown number of results which are computed. If you want to get the result, call the function explicitly, no?

**Comment by adamjhc** [comment]
Somehow didn't think of this... this would work for relatively quick functions but would be a pain for slower ones.

Thanks
